In [1]:
from collections import namedtuple
from collections.abc import Sequence
from multiprocessing import cpu_count
from pathlib import Path

import anndata as ad
import decoupler as dc
import pandas as pd
from pydeseq2.dds import DeseqDataSet
from pydeseq2.default_inference import DefaultInference
from pydeseq2.ds import DeseqStats

In [2]:
import scanpy as sc

In [5]:
import muon as mu

2025-12-04 12:00:05.358053: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-12-04 12:00:13.006773: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-12-04 12:00:45.807772: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

In [6]:
project_folder = Path.home().joinpath("eternal_gallery", "ana_multiome")
data_folder = project_folder / "data"
rnaseq_folder = data_folder / "rnaseq"

In [18]:
bcells = mu.read(rnaseq_folder / "bcells_20251107_final_rna_adt_PAM_ab.h5mu")

In [57]:
metadata_df = pd.read_csv(data_folder/"metadata"/"metadata_pam.csv", index_col="PAM_ID")

In [58]:
bcells["rna"].obs.columns

Index(['n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt',
       'sample', 'sample_name', 'visit_ref', 'subject_ref', 'disease_class',
       'ethnicity', 'batch', 'leiden', 'type_label', 'leiden_wnn',
       'level1_labels', 'level2_labels', 'level3_labels'],
      dtype='object')

In [62]:
for x in [
        "vaeda_scores",
        "vaeda_calls",
        "c19_healthy_majority",
        "c19_healthy_predicted",
        "c19_healthy_over_clustering",
        "immune_low_majority",
        "immune_low_predicted",
        "immune_low_over_clustering",
        "leiden_wnn_1.5",
        "leiden_wnn_1.2",
        "leiden_wnn_1.0",
        "leiden_wnn_0.9",
        "leiden_wnn_0.8",
        "leiden_wnn_0.7",
        "leiden_wnn_0.6",
        "leiden_wnn_0.5",
        "leiden_wnn_2.0",
    ]:
    if x in bcells["rna"].obs.columns:
        bcells["rna"].obs.drop(
            columns=[x],
            inplace=True
        )

In [14]:
compare_col="Disease_class",
design_factors=["Disease_class", "PC1"],
continuous_factors=["PC1"],
cell_type_of_interest="Memory",
cell_type_obs_col="type_label",
layer="counts"

In [22]:
stuff = pseudobulk_deg_process(
    obj=bcells["rna"],
    metadata_df=metadata_df,
    comparisons=[
        {"ref": "Neg", "exp": "Pos"},
        {"ref": "Neg", "exp": "ILE"},
        {"ref": "Neg", "exp": "SLE"},
        {"ref": "Pos", "exp": "ILE"},
        {"ref": "Pos", "exp": "SLE"},
        {"ref": "ILE", "exp": "SLE"}
    ],
    compare_col="Disease_class",
    design_factors=["Disease_class", "PC1"],
    continuous_factors=["PC1"],
    cell_type_of_interest="Memory",
    cell_type_obs_col="type_label",
    layer="counts"
)

/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: continuous_factors is deprecated and will soon be removed.Continuous factors are now automatically detected from the design,or can be cast to categorical using the C() operator in the formula
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
  dds = DeseqDataSet(
Fitting size factors...
... done in 0.04 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.92 seconds.

Fitting dispersion trend curve...
... done in 0.20 seconds.

Fitting MAP dispersions...
... done in 1.02 seconds.

Fitting LFCs...
... done in 1.28 seconds.

Calculating cook's distance...
... done in 0.10 seconds.

Replacing 0 outlier genes.

/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: continuous_factors is deprecated and will soon be removed.Continuous factors are now automatically detected from the design,or can be cast to categorical using the C() operator in the formula
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
  dds = DeseqDataSet(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.21 seconds.

Fitting MAP dispersions...
... done in 1.05 seconds.

Fitting LFCs...
... done in 1.18 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 0 outlier genes.

/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: continuous_factors is deprecated and will soon be removed.Continuous factors are now automatically detected from the design,or can be cast to categorical using the C() operator in the formula
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
  dds = DeseqDataSet(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.89 seconds.

Fitting dispersion trend curve...
... done in 0.20 seconds.

Fitting MAP dispersions...
... done in 1.00 seconds.

Fitting LFCs...
... done in 0.98 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 0 outlier genes.

/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: continuous_factors is deprecated and will soon be removed.Continuous factors are now automatically detected from the design,or can be cast to categorical using the C() operator in the formula
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
  dds = DeseqDataSet(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.20 seconds.

Fitting MAP dispersions...
... done in 1.01 seconds.

Fitting LFCs...
... done in 1.20 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 0 outlier genes.

/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: continuous_factors is deprecated and will soon be removed.Continuous factors are now automatically detected from the design,or can be cast to categorical using the C() operator in the formula
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
  dds = DeseqDataSet(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.87 seconds.

Fitting dispersion trend curve...
... done in 0.21 seconds.

Fitting MAP dispersions...
... done in 1.02 seconds.

Fitting LFCs...
... done in 1.03 seconds.

Calculating cook's distance...
... done in 0.02 seconds.

Replacing 0 outlier genes.

/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: continuous_factors is deprecated and will soon be removed.Continuous factors are now automatically detected from the design,or can be cast to categorical using the C() operator in the formula
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: ref_level is deprecated and no longer has any effect. It will beremoved in a future release.
  dds = DeseqDataSet(
/tmp/ipykernel_523101/3449017235.py:46: DeprecationWarning: design_factors is deprecated and will soon be removed.Please consider providing a formulaic formula using the design argumentinstead.
  dds = DeseqDataSet(
Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

Fitting dispersions...
... done in 0.88 seconds.

Fitting dispersion trend curve...
... done in 0.22 seconds.

Fitting MAP dispersions...
... done in 1.02 seconds.

Fitting LFCs...
... done in 1.23 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 0 outlier genes.

In [26]:
stuff["Neg_vs_Pos"].results_df

              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
UQCRB       284.718308        0.104512  0.171164  0.610594  0.541469  0.784900
ADGRV1        0.309245        0.270712  1.198891  0.225802  0.821355       NaN
LINC01993     0.099920        0.224615  2.150752  0.104436  0.916824       NaN
AC021321.2    0.008842       -0.421782  4.842182 -0.087106  0.930587       NaN
AC020900.1    0.213539       -0.022314  1.357456 -0.016438  0.986885       NaN
...                ...             ...       ...       ...       ...       ...
ARID1A       29.180560        0.475721  0.247356  1.923227  0.054452  0.375224
ELF3          0.040477        0.263349  3.885342  0.067780  0.945961       NaN
CNN3          2.517070       -0.241479  0.701514 -0.344225  0.730677       NaN
RAB3C         0.512981       -1.289967  0.993489 -1.298421  0.194143       NaN
SLC18A2       0.250954        0.409953  1.184152  0.346200  0.729193       NaN

[25085 rows x 6 columns]

In [17]:
memory = bcells['rna'][bcells['rna'].obs.query("type_label == 'Memory'").index,:]

In [66]:
metadata_df.columns = metadata_df.columns.str.lower()

In [67]:
metadata_df.rename(columns={"subjectref":"subject_ref"}, inplace=True)

In [68]:
metadata_df.set_index("subject_ref").head()

            self_race  age disease_class       pc1
subject_ref
OCRD|0786          AA   53           SLE -0.119112
CE|541417          AA   28           Neg -0.195063
OCRD|1673          AA   50           ILE -0.045099
CH|551432          AA   57           Pos -0.144351
OCRD|1681          EA   51           ILE  0.136603

In [23]:
for col in metadata_df.columns:
    if col not in memory.obs.columns:
        memory.obs = memory.obs.merge(metadata_df.loc[:,[col, "subject_ref"]].set_index("subject_ref"), left_on="subject_ref", right_index=True)

In [24]:
memory.obs.head()

,n_genes_by_counts,total_counts,total_counts_mt,pct_counts_mt,sample,sample_name,visit_ref,subject_ref,disease_class,ethnicity,batch,leiden,type_label,leiden_wnn,level1_labels,level2_labels,level3_labels,self_race,age,pc1
AAACGGGAGTCCGGTC-1_PAM46,1466,3138.0,24.0,0.764818,PAM46,PAM46,OCRD|1691|2020-09-25,OCRD|1691,ILE,EA,19b,13,Memory,2,B cells,Memory B,Unswitched Memory,EA,50,0.133658
AAGGAGCGTTCAGTAC-1_PAM46,1540,3567.0,44.0,1.233530,PAM46,PAM46,OCRD|1691|2020-09-25,OCRD|1691,ILE,EA,19b,13,Memory,2,B cells,Memory B,CM1,EA,50,0.133658
ACGGAGACAACACCTA-1_PAM46,2578,6020.0,138.0,2.292359,PAM46,PAM46,OCRD|1691|2020-09-25,OCRD|1691,ILE,EA,19b,13,Memory,2,B cells,Naive B,CN6,EA,50,0.133658
ACTGAGTCACAGACAG-1_PAM46,2111,4621.0,93.0,2.012551,PAM46,PAM46,OCRD|1691|2020-09-25,OCRD|1691,ILE,EA,19b,13,Memory,2,B cells,Naive B,CN5,EA,50,0.133658
AGAATAGAGAAGGACA-1_PAM46,2198,5222.0,71.0,1.359632,PAM46,PAM46,OCRD|1691|2020-09-25,OCRD|1691,ILE,EA,19b,16,Memory,2,B cells,Naive B,CN5,EA,50,0.133658

In [25]:
memory

AnnData object with n_obs × n_vars = 12996 × 36601
    obs: 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'sample', 'sample_name', 'visit_ref', 'subject_ref', 'disease_class', 'ethnicity', 'batch', 'leiden', 'type_label', 'leiden_wnn', 'level1_labels', 'level2_labels', 'level3_labels', 'self_race', 'age', 'pc1'
    var: 'gene_ids', 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'batch_colors', 'dendrogram_leiden_wnn_2.0', 'hvg', 'log1p', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [50]:
inference = DefaultInference(n_cpus=cpu_count())

In [27]:
memory

AnnData object with n_obs × n_vars = 12996 × 36601
    obs: 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'sample', 'sample_name', 'visit_ref', 'subject_ref', 'disease_class', 'ethnicity', 'batch', 'leiden', 'type_label', 'leiden_wnn', 'level1_labels', 'level2_labels', 'level3_labels', 'self_race', 'age', 'pc1'
    var: 'gene_ids', 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'batch_colors', 'dendrogram_leiden_wnn_2.0', 'hvg', 'log1p', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'connectivities', 'distances'

In [28]:
memory.X = memory.layers["counts"].toarray()

In [29]:
subset_bulked = dc.pp.pseudobulk(memory, sample_col="sample_name", groups_col=None, layer="counts")

In [30]:
subset_bulked

AnnData object with n_obs × n_vars = 55 × 36601
    obs: 'sample_name', 'sample', 'visit_ref', 'subject_ref', 'disease_class', 'ethnicity', 'batch', 'type_label', 'level1_labels', 'self_race', 'age', 'pc1', 'psbulk_cells', 'psbulk_counts'
    var: 'gene_ids', 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    layers: 'psbulk_props'

In [33]:
bcells["rna"].obs.dtypes

n_genes_by_counts                 int32
total_counts                    float32
total_counts_mt                 float32
pct_counts_mt                   float32
vaeda_scores                    float64
vaeda_calls                    category
sample                         category
sample_name                    category
visit_ref                      category
subject_ref                    category
disease_class                  category
ethnicity                      category
batch                          category
leiden                         category
c19_healthy_majority           category
c19_healthy_predicted          category
c19_healthy_over_clustering    category
immune_low_majority            category
immune_low_predicted           category
immune_low_over_clustering     category
type_label                     category
leiden_wnn                     category
level1_labels                  category
leiden_wnn_1.5                 category
leiden_wnn_1.2                 category
leiden_wnn_1.0                 category
leiden_wnn_0.9                 category
leiden_wnn_0.8                 category
leiden_wnn_0.7                 category
leiden_wnn_0.6                 category
leiden_wnn_0.5                 category
leiden_wnn_2.0                 category
level2_labels                  category
level3_labels                  category
dtype: object

In [34]:
metadata_df.dtypes

subject_ref       object
self_race         object
age                int64
disease_class     object
pc1              float64
dtype: object

In [31]:
subset_bulked.obs.dtypes

sample_name      category
sample           category
visit_ref        category
subject_ref      category
disease_class    category
ethnicity        category
batch            category
type_label       category
level1_labels    category
self_race        category
age              category
pc1              category
psbulk_cells      float64
psbulk_counts     float64
dtype: object

In [48]:
subset_bulked.obs["pc1"].dtype == "category"

True

In [40]:
from formulaic.parser import DefaultFormulaParser
from formulaic_contrasts import FormulaicContrasts

In [37]:
design = "~disease_class+age+pc1"

In [42]:
pf = FormulaicContrasts(subset_bulked.obs, design)

In [44]:
pf.design_matrix.shape[1]

87

In [45]:
np.linalg.matrix_rank(pf.design_matrix)

np.int64(55)

In [46]:
formula = DefaultFormulaParser(design)

In [135]:
exprs: pd.DataFrame = pd.DataFrame(
    data=subset_bulked.X, index=subset_bulked.obs_names, columns=subset_bulked.var_names
)

In [137]:
exprs.head()

,UQCRB,AC106017.2,ADGRV1,LINC01993,AC021321.2,AC020900.1,AL162493.1,USP12-AS2,CHFR,CDC42-IT1,...,CD300LD,PLXNB1,ARID1A,ELF3,CNN3,AL034376.2,RAB3C,SLC18A2,LINC00459,AC010503.2
PAM46,92.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,11.0,0.0,...,0.0,0.0,34.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0
PAM57,293.0,0.0,2.0,0.0,0.0,0.0,0.0,3.0,4.0,0.0,...,0.0,0.0,5.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0
PAM56,43.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0.0,0.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
PAM34,358.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,14.0,0.0,...,0.0,0.0,36.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
PAM51,305.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,20.0,1.0,...,0.0,0.0,66.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0

In [138]:
exprs.sum(axis=0).where(lambda x: x == 0).replace({np.nan: False, 0.0: True}).sum()

np.int64(11516)

In [139]:
(exprs.sum(axis=0) == np.sum(exprs, axis=0)).all()

np.True_

In [114]:
memory.var["all_zeros"] = exprs.sum(axis=0).where(lambda x: x == 0).replace({np.nan: False, 0.0: True})[memory.var_names]
memory.var["no_deviance"] = exprs.std(axis=0).where(lambda x: x == 0).replace({np.nan: False, 0.0: True})[memory.var_names]

In [115]:
mu.pp.filter_var(memory, var="all_zeros", func=lambda x: ~x)

In [116]:
mu.pp.filter_var(memory, var="no_deviance", func=lambda x: ~x)

In [190]:
for stat, func in zip(["all_zeros", "no_deviance"], [np.sum, np.std], strict=True):
    subset_bulked.var[stat] = func(exprs, axis=0).where(lambda x: x == 0).replace({np.nan: False, 0.0: True})[subset_bulked.var_names]
    mu.pp.filter_var(subset_bulked, var=stat, func=lambda x: ~x)

In [141]:
subset_bulked

AnnData object with n_obs × n_vars = 55 × 25085
    obs: 'sample_name', 'sample', 'visit_ref', 'subject_ref', 'disease_class', 'ethnicity', 'batch', 'type_label', 'level1_labels', 'self_race', 'age', 'pc1', 'psbulk_cells', 'psbulk_counts'
    var: 'gene_ids', 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'all_zeros', 'no_deviance'
    layers: 'psbulk_props'

In [186]:
subset_bulked.obs.head().dtypes

sample_name      category
sample           category
visit_ref        category
subject_ref      category
disease_class    category
ethnicity        category
batch            category
type_label       category
level1_labels    category
self_race        category
age              category
pc1              category
psbulk_cells      float64
psbulk_counts     float64
size_factors      float64
replaceable          bool
dtype: object

In [191]:
for x in ["age", "pc1"]:
    subset_bulked.obs[x] = subset_bulked.obs[x].astype(float)

In [196]:
dds = DeseqDataSet(
    counts=exprs2, design="~disease_class+age+pc1", metadata=subset_bulked.obs, n_cpus=8, 
)

In [197]:
dds.deseq2()

Fitting size factors...
... done in 0.02 seconds.

Using None as control genes, passed at DeseqDataSet initialization

/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: overflow encountered in multiply
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
Fitting dispersions...
... done in 1.25 seconds.

Fitting dispersion trend curve...
... done in 0.23 seconds.

Fitting MAP dispersions...
... done in 1.48 seconds.

Fitting LFCs...
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
... done in 1.89 seconds.

Calculating cook's distance...
... done in 0.04 seconds.

Replacing 0 outlier genes.

In [198]:
stat_res = DeseqStats(
    dds, contrast=["disease_class", "SLE", "Neg"], inference=inference, 
)

In [200]:
res = stat_res.summary()

Log2 fold change & Wald test p-value: disease_class SLE vs Neg
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
UQCRB       281.765226        0.038628  0.177102  0.218113  0.827341  0.984565
ADGRV1        0.290148        0.475409  1.263016  0.376407  0.706614       NaN
LINC01993     0.085606        1.326493  2.433731  0.545045  0.585723       NaN
AC021321.2    0.007580        1.109349  4.934978  0.224793  0.822140       NaN
AC020900.1    0.195615        0.886015  1.483686  0.597172  0.550393       NaN
...                ...             ...       ...       ...       ...       ...
ARID1A       30.578179       -0.177809  0.247794 -0.717569  0.473023  0.935732
ELF3          0.081451        1.394977  2.711560  0.514456  0.606934       NaN
CNN3          2.307878       -0.389135  0.737550 -0.527605  0.597774  0.957687
RAB3C         0.501254       -0.334635  1.047535 -0.319450  0.749385       NaN
SLC18A2       0.241788        0.275734  1.271260  0.216898  0.828288       NaN

[25085 rows x 6 columns]

In [184]:
res = stat_res.summary()

Running Wald tests...

Log2 fold change & Wald test p-value: disease_class SLE vs Neg
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
UQCRB       281.765226        0.013222  0.155486  0.085037  0.932232  0.999629
ADGRV1        0.290148        0.361293  1.231628  0.293346  0.769258       NaN
LINC01993     0.085606        1.074566  2.524538  0.425648  0.670364       NaN
AC021321.2    0.007580        1.142718  4.374600  0.261216  0.793926       NaN
AC020900.1    0.195615        0.622378  1.603683  0.388093  0.697947       NaN
...                ...             ...       ...       ...       ...       ...
ARID1A       30.578179       -0.107540  0.216117 -0.497598  0.618767  0.987862
ELF3          0.081451        1.610467  2.828405  0.569390  0.569091       NaN
CNN3          2.307878       -0.595224  0.653709 -0.910533  0.362542  0.955755
RAB3C         0.501254       -0.866098  1.007694 -0.859485  0.390073       NaN
SLC18A2       0.241788       -0.058634  1.328141 -0.044147  0.964787       NaN

[25085 rows x 6 columns]

... done in 0.80 seconds.

In [204]:
stat_res.results_df.query("padj < 0.05").head()

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
HSP90AA1,268.226025,-1.198838,0.308647,-3.884166,1.026817e-04,3.361474e-02
HSPA1B,45.456185,-5.922569,0.838947,-7.059529,1.670678e-12,1.039161e-08
DNAJB1,71.018196,-3.715963,0.595013,-6.245178,4.233188e-10,1.755362e-06
EIF2AK2,47.274788,1.346235,0.314945,4.274516,1.915530e-05,9.928830e-03
SC5D,6.227238,-1.500350,0.378865,-3.960120,7.491205e-05,2.823957e-02

In [158]:
stat_res.results_df.query("padj < 0.05")

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
TNFRSF18,3.767355,-2.946568,0.659521,-4.467740,7.905040e-06,0.004683
HSPA1B,15.281278,-3.728472,0.624542,-5.969930,2.373558e-09,0.000015
DNAJB1,26.090291,-1.303544,0.341755,-3.814263,1.365900e-04,0.032677
EIF2AK2,47.274788,1.334238,0.282370,4.725135,2.299630e-06,0.001907
SC5D,6.227238,-1.286121,0.342775,-3.752090,1.753663e-04,0.040399
...,...,...,...,...,...,...
GCSAM,12.163347,1.558245,0.327951,4.751456,2.019574e-06,0.001795
XAF1,74.105555,1.888235,0.368558,5.123303,3.002287e-07,0.000467
SUB1,222.114083,0.514640,0.134875,3.815673,1.358125e-04,0.032677
SERTAD1,11.765363,-1.508269,0.348156,-4.332161,1.476529e-05,0.007986
PPFIBP2,17.694045,-1.183907,0.317674,-3.726801,1.939257e-04,0.042472

In [49]:
from collections.abc import Sequence

In [144]:
def pseudobulk_deg_process(
    adata: ad.AnnData,
    compare_col: str,
    design: str,
    comparisons: dict[str, str] | Sequence[dict[str, str]],
    cell_type_of_interest: str | None = None,
    cell_type_obs_col: str | None = None,
    sample_name_col: str = "sample_name",
    min_sum_counts: float = 1.0,
    min_std: float = 0.1,
    layer: str | None = None,
    n_cpus: int = -1,
    output_dir: Path | None = None,
) -> dict[str, DeseqStats]:
    """
    Parameters
    ----------
    adata : ad.AnnData
        AnnData object to examine
    compare_col : str
        Column in `adata.obs` to use when grouping cells for comparison
    design : str
        Design formula to use for analysis. Like an R-style formula. For example: "~disease"
    comparisons : dict[str, str], Sequence[dict[str, str]]
        What groups to compare and how to compare them. This MUST be a dictionary in the form of
        `{"ref": "controls", "test": "test_group"}`
    cell_type_of_interest : str, optional
        A value in `cell_type_obs_col` to subset `adata` by
    cell_type_obs_col : str, optional
        A column in `adata.obs` to look for values by which to subset `adata`
    sample_name_col : str, default = "sample_name"
        Name of column in `adata.obs` to be used to group cells when pseudobulking the sample
    min_sum_counts : float, default = 1.0
        Count threshold above which genes much be for their inclusion in analysis.
        Genes with a count below this will be removed.
    min_std : float, default = 0.1
        Standard deviation threshold above which genes much be for their inclusion in analysis.
        Genes with a stdev below this will be removed.
    layer : str, optional
        Layer to use for the counts
    n_cpus : int, default = -1 (i.e. use all available cpus)
        Number of CPUs to use when running pydeseq2 functions.
    output_dir : Path, optional
        Path to where DEG results should be saved.

    Returns
    -------
    A dictionary with the comparison name as keys in the form of "ref_vs_test" and the DeseqStats object as value

    Example
    -------
    >>> res = pseudobulk_deg_process(
            adata=bcell_rna,
            design=~disease+age,
            comparisons=[
                {"ref": "Neg", "test": "Pos"},
                {"ref": "Neg", "test": "ILE"},
                {"ref": "Neg", "test": "SLE"},
                {"ref": "Pos", "test": "ILE"},
                {"ref": "Pos", "test": "SLE"},
                {"ref": "ILE", "test": "SLE"}
            ],
            cell_type_of_interest="Memory",
            cell_type_obs_col="type_label",
            layer="counts"
        )
    """
    # TODO: handle errors and a lot of checking and messages!

    if n_cpus == -1:
        n_cpus = cpu_count()

    check_formula(adata.obs, design)

    if cell_type_of_interest:
        if cell_type_obs_col is None:
            msg = f"{cell_type_of_interest} was passed as the 'cell_type_of_interest' argument, but no 'cell_type_obs_col' was given!"
            raise KeyError(msg)
        if any(adata.obs[cell_type_obs_col] == cell_type_of_interest):
            subset: ad.AnnData = adata[adata.obs[cell_type_obs_col] == cell_type_of_interest, :]
        else:
            msg = (
                f"There do not appear to be any cells where the value of '{cell_type_obs_col}' is '{cell_type_of_interest}'"
            )
            raise ValueError(msg)
    else:
        subset = adata

    subset_bulked: ad.AnnData = dc.pp.pseudobulk(adata=subset, sample_col=sample_name_col, groups_col=None, layer=layer)

    # I don't *think* decoupler can return a sparse pseudobulked object, but do I know for sure? No.
    if issparse(subset_bulked.X):
        msg = "PyDESeq2 doesn't work with sparse matrices. Densifying X"
        warnings.warn(msg, stacklevel=2)
        subset_bulked.X = subset_bulked.X.toarray()  # pyright: ignore[reportOptionalMemberAccess, reportAttributeAccessIssue]

    exprs: pd.DataFrame = pd.DataFrame(
        data=subset_bulked.X, index=subset_bulked.obs_names, columns=subset_bulked.var_names
    )

    # dumping genes with no detectable expression and no variance
    for stat, func, thresh in zip(["below_zero_thresh", "below_deviance_thresh"], [np.sum, np.std], [min_sum_counts, min_std], strict=True):
        subset_bulked.var[stat] = (
            func(exprs, axis=0).where(lambda x: x < thresh).replace({np.nan: False, 0.0: True})[subset_bulked.var_names]
        )
        mu.pp.filter_var(subset_bulked, var=stat, func=lambda x: ~x)

    if not full_rank_design(subset_bulked, design):
        msg = (
            "One or more terms in the design formula is causing the design matrix to not be full rank. "
            "Attempting to correct an issue with `decoupler` changing continuous variables to categorical..."
        )
        warnings.warn(msg, stacklevel=2)
        try:
            subset_bulked.obs = fix_continuous_vars(subset_bulked.obs, adata.obs, design)
        except FormulaicError as err:
            msg = "Something is wrong with the design formula. Stopping as PyDESeq2 WILL fail"
            raise FormulaicError(msg) from err

    inference = DefaultInference(n_cpus=cpu_count())

    dds = DeseqDataSet(
        adata=subset_bulked,
        design=design,
        refit_cooks=True,
        inference=inference,
    )

    dds.deseq2()

    res_dict = {}
    # start looping through comparisons
    if isinstance(comparisons, Sequence):
        for compare in comparisons:
            stat_res = DeseqStats(
                dds, contrast=[compare_col, compare["test"], compare["ref"]], inference=inference, n_cpus=n_cpus
            )

            stat_res.summary()
            # add results to res_dict
            res_dict[f"{compare['ref']}_vs_{compare['test']}"] = stat_res

            if output_dir:
                stat_res.results_df.to_csv(
                    output_dir.joinpath(
                        f"{cell_type_of_interest}_{cell_type_obs_col}_{compare['ref']}{compare['test']}.csv".replace(
                            " ", "_"
                        )
                    )
                )
    else:
        stat_res = DeseqStats(
            dds, contrast=[compare_col, comparisons["test"], comparisons["ref"]], inference=inference, n_cpus=n_cpus
        )

        stat_res.summary()
        # add results to res_dict
        res_dict[f"{comparisons['ref']}_vs_{comparisons['test']}"] = stat_res

        if output_dir:
            stat_res.results_df.to_csv(
                output_dir.joinpath(
                    f"{cell_type_of_interest}_{cell_type_obs_col}_{comparisons['ref']}{comparisons['test']}.csv".replace(
                        " ", "_"
                    )
                )
            )
    return res_dict

In [150]:
# based on the version in PyDESeq2. Copied and not imported because it is a private method
def full_rank_design(adata: ad.AnnData, formula: str) -> bool:
    """Check that the design matrix has full column rank."""
    design_matrix = FormulaicContrasts(data=adata.obs, design=formula).design_matrix
    rank = np.linalg.matrix_rank(A=design_matrix)
    num_vars = design_matrix.shape[1]

    if rank < num_vars:
        return False
    else:
        return True

In [146]:
def extract_terms(formula: str) -> list[str]:
    return [
        token.token
        for token in DefaultFormulaParser().get_tokens(formula)
        if token.kind.value == "name"  # pyright: ignore[reportOptionalMemberAccess]
    ]

In [147]:
def fix_continuous_vars(obs, prev_obs, formula) -> pd.DataFrame:
    design_terms = extract_terms(formula)
    for term in design_terms:
        if (obs[term].dtype == "category") & (obs[term].dtype != prev_obs[term].dtype):
            obs[term] = obs[term].astype(prev_obs[term].dtype)
    return obs

In [148]:
def check_formula(obs, formula) -> None:
    design_terms = extract_terms(formula)
    not_found = [term for term in design_terms if term not in obs.columns]
    if len(not_found) > 0:
        msg = f"The terms {', '.join(not_found)} are not present in the anndata object's obs columns"
        raise pd.errors.InvalidColumnName(msg)

In [69]:
for col in metadata_df.columns:
    if col not in bcells["rna"].obs.columns:
        bcells["rna"].obs = bcells["rna"].obs.merge(metadata_df.loc[:,[col, "subject_ref"]].set_index("subject_ref"), left_on="subject_ref", right_index=True)

In [71]:
from scipy.sparse import issparse
from formulaic.errors import FormulaicError
from formulaic.parser import DefaultFormulaParser
from formulaic_contrasts import FormulaicContrasts

In [151]:
pseudobulk_deg_process(adata=bcells["rna"], compare_col="disease_class", design="~disease_class+age+pc1", comparisons={"ref":"Neg", "test": "SLE"}, cell_type_of_interest="Memory", cell_type_obs_col="type_label", sample_name_col="sample_name",layer="counts", n_cpus=8)

Using None as control genes, passed at DeseqDataSet initialization

/tmp/ipykernel_29811/3776959764.py:1: UserWarning: One or more terms in the design formula is causing the design matrix to not be full rank. Attempting to correct an issue with `decoupler` changing continuous variables to categorical...
  pseudobulk_deg_process(adata=bcells["rna"], compare_col="disease_class", design="~disease_class+age+pc1", comparisons={"ref":"Neg", "test": "SLE"}, cell_type_of_interest="Memory", cell_type_obs_col="type_label", sample_name_col="sample_name",layer="counts", n_cpus=8)
Fitting size factors...
... done in 0.02 seconds.

/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: overflow encountered in multiply
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
Fitting dispersions...
... done in 0.86 seconds.

Fitting dispersion trend curve...
... done in 0.20 seconds.

Fitting MAP dispersions...
... done in 0.99 seconds.

Fitting LFCs...
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
... done in 1.28 seconds.

Calculating cook's distance...
... done in 0.03 seconds.

Replacing 0 outlier genes.

Running Wald tests...

Log2 fold change & Wald test p-value: disease_class SLE vs Neg
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
UQCRB       281.765226        0.038628  0.177102  0.218113  0.827341  0.984565
ADGRV1        0.290148        0.475409  1.263016  0.376407  0.706614       NaN
LINC01993     0.085606        1.326493  2.433731  0.545045  0.585723       NaN
AC021321.2    0.007580        1.109349  4.934978  0.224793  0.822140       NaN
AC020900.1    0.195615        0.886015  1.483686  0.597172  0.550393       NaN
...                ...             ...       ...       ...       ...       ...
ARID1A       30.578179       -0.177809  0.247794 -0.717569  0.473023  0.935732
ELF3          0.081451        1.394977  2.711560  0.514456  0.606934       NaN
CNN3          2.307878       -0.389135  0.737550 -0.527605  0.597774  0.957687
RAB3C         0.501254       -0.334635  1.047535 -0.319450  0.749385       NaN
SLC18A2       0.241788        0.275734  1.271260  0.216898  0.828288       NaN

[25085 rows x 6 columns]

... done in 1.96 seconds.

{'Neg_vs_SLE': <pydeseq2.ds.DeseqStats at 0x769ba8687320>}

In [73]:
adata=bcells["rna"]
compare_col="disease_class"
design="~disease_class+age+pc1"
comparisons={"ref":"Neg", "test": "SLE"}
cell_type_of_interest="Memory"
cell_type_obs_col="type_label"
sample_name_col="sample_name"
layer="counts"
n_cpus=8

In [75]:
if n_cpus == -1:
    n_cpus = cpu_count()

In [76]:
check_formula(adata.obs, design)

In [78]:
if cell_type_of_interest:
    if cell_type_obs_col is None:
        msg = f"{cell_type_of_interest} was passed as the 'cell_type_of_interest' argument, but no 'cell_type_obs_col' was given!"
        raise KeyError(msg)
    if any(adata.obs[cell_type_obs_col] == cell_type_of_interest):
        subset: ad.AnnData = adata[adata.obs[cell_type_obs_col] == cell_type_of_interest, :]
    else:
        msg = (
            f"There do not appear to be any cells where the value of '{cell_type_obs_col}' is '{cell_type_of_interest}'"
        )
        raise ValueError(msg)
else:
    subset = adata

In [94]:
subset_bulked: ad.AnnData = dc.pp.pseudobulk(adata=subset, sample_col=sample_name_col, groups_col=None, layer=layer)

In [95]:
# I don't *think* decoupler can return a sparse pseudobulked object, but do I know for sure? No.
if issparse(subset_bulked.X):
    msg = "PyDESeq2 doesn't work with sparse matrices. Densifying X"
    warnings.warn(msg, stacklevel=2)
    subset_bulked.X = subset_bulked.X.toarray()  # pyright: ignore[reportOptionalMemberAccess, reportAttributeAccessIssue]

In [96]:
exprs: pd.DataFrame = pd.DataFrame(
    data=subset_bulked.X, index=subset_bulked.obs_names, columns=subset_bulked.var_names
)

In [97]:
min_sum_counts: float = 1.0
min_std: float = 0.1

In [98]:
# dumping genes with no detectable expression and no variance
for stat, func, thresh in zip(["below_zero_thresh", "below_deviance_thresh"], [np.sum, np.std], [min_sum_counts, min_std], strict=True):
    print(f"{stat=}{func=}{thresh=}")
    subset_bulked.var[stat] = (
        func(exprs, axis=0).where(lambda x: x < thresh).replace({np.nan: False, 0.0: True})[subset_bulked.var_names]
    )
    mu.pp.filter_var(subset_bulked, var=stat, func=lambda x: ~x)

stat='below_zero_thresh'func=<function sum at 0x769e50150670>thresh=1.0
stat='below_deviance_thresh'func=<function std at 0x769e50152af0>thresh=0.1

In [99]:
subset_bulked

AnnData object with n_obs × n_vars = 55 × 25085
    obs: 'sample_name', 'sample', 'visit_ref', 'subject_ref', 'disease_class', 'ethnicity', 'batch', 'type_label', 'level1_labels', 'self_race', 'age', 'pc1', 'psbulk_cells', 'psbulk_counts'
    var: 'gene_ids', 'feature_types', 'genome', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'below_zero_thresh', 'below_deviance_thresh'
    layers: 'psbulk_props'

In [104]:
import warnings

In [105]:
if not full_rank_design(subset_bulked.obs, design):
    msg = (
        "One or more terms in the design formula is causing the design matrix to not be full rank. "
        "Attempting to correct an issue with `decoupler` changing continuous variables to categorical..."
    )
    warnings.warn(msg, stacklevel=2)
    try:
        subset_bulked.obs = fix_continuous_vars(subset_bulked.obs, adata.obs, design)
    except FormulaicError as err:
        msg = "Something is wrong with the design formula. Stopping as PyDESeq2 WILL fail"
        raise FormulaicError(msg) from err

/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3699: UserWarning: One or more terms in the design formula is causing the design matrix to not be full rank. Attempting to correct an issue with `decoupler` changing continuous variables to categorical...
  exec(code_obj, self.user_global_ns, self.user_ns)

In [107]:
inference = DefaultInference(n_cpus=cpu_count())

In [108]:
dds = DeseqDataSet(
    adata=subset_bulked,
    design=design,
    refit_cooks=True,
    inference=inference,
)

In [109]:
dds.deseq2()

Fitting size factors...

Using None as control genes, passed at DeseqDataSet initialization

... done in 0.38 seconds.

/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: overflow encountered in multiply
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
Fitting dispersions...
... done in 0.85 seconds.

Fitting dispersion trend curve...
... done in 0.22 seconds.

Fitting MAP dispersions...
... done in 0.98 seconds.

Fitting LFCs...
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:380: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:234: RuntimeWarning: invalid value encountered in multiply
  - counts * np.log(mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:232: RuntimeWarning: invalid value encountered in subtract
  -logbinom
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:384: RuntimeWarning: overflow encountered in exp
  mu_ = np.maximum(size_factors * np.exp(X @ beta), min_mu)
/mnt/d/eternal_gallery/ana_multiome/.venv/lib/python3.12/site-packages/pydeseq2/utils.py:387: RuntimeWarning: invalid value encountered in divide
  + ((1 / disp + counts) * mu_ / (1 / disp + mu_)) @ X
... done in 1.03 seconds.

Calculating cook's distance...
... done in 0.13 seconds.

Replacing 0 outlier genes.

In [110]:
res_dict = {}

In [138]:
def iter_comparisons(dds, comparisons, inference, n_cpus, output_dir=None):
    stat_res = DeseqStats(
        dds, contrast=[compare_col, comparisons["test"], comparisons["ref"]], inference=inference, n_cpus=n_cpus
    )
    
    stat_res.summary()
    if output_dir:
        stat_res.results_df.to_csv(
            output_dir.joinpath(
                f"{cell_type_of_interest}_{cell_type_obs_col}_{comparisons['ref']}{comparisons['test']}.csv".replace(
                    " ", "_"
                )
            )
        )    
    # add results to res_dict
    return f"{comparisons['ref']}_vs_{comparisons['test']}", stat_res

In [143]:
type(comparisons)

dict

In [142]:
{k: v for k, v in [iter_comparisons(dds, x, inference, n_cpus) for x in [comparisons]]}

Running Wald tests...

Log2 fold change & Wald test p-value: disease_class SLE vs Neg
              baseMean  log2FoldChange     lfcSE      stat    pvalue      padj
UQCRB       281.765226        0.038628  0.177102  0.218113  0.827341  0.984565
ADGRV1        0.290148        0.475409  1.263016  0.376407  0.706614       NaN
LINC01993     0.085606        1.326493  2.433731  0.545045  0.585723       NaN
AC021321.2    0.007580        1.109349  4.934978  0.224793  0.822140       NaN
AC020900.1    0.195615        0.886015  1.483686  0.597172  0.550393       NaN
...                ...             ...       ...       ...       ...       ...
ARID1A       30.578179       -0.177809  0.247794 -0.717569  0.473023  0.935732
ELF3          0.081451        1.394977  2.711560  0.514456  0.606934       NaN
CNN3          2.307878       -0.389135  0.737550 -0.527605  0.597774  0.957687
RAB3C         0.501254       -0.334635  1.047535 -0.319450  0.749385       NaN
SLC18A2       0.241788        0.275734  1.271260  0.216898  0.828288       NaN

[25085 rows x 6 columns]

... done in 0.62 seconds.

{'Neg_vs_SLE': <pydeseq2.ds.DeseqStats at 0x769ba873d1c0>}

In [111]:
# start looping through comparisons
for compare in comparisons:
    stat_res = DeseqStats(
        dds, contrast=[compare_col, compare["test"], compare["test"]], inference=inference, n_cpus=n_cpus
    )

    stat_res.summary()
    # add results to res_dict
    res_dict[f"{compare['ref']}_vs_{compare['test']}"] = stat_res

    if output_dir:
        stat_res.results_df.to_csv(
            output_dir.joinpath(
                f"{cell_type_of_interest}_{cell_type_obs_col}_{compare['ref']}{compare['test']}.csv".replace(
                    " ", "_"
                )
            )
        )

TypeError: string indices must be integers, not 'str'

In [153]:
mu.pp.filter_obs(bcells, "type_label", func=lambda x: x == "Memory")

In [156]:
bcells.write("/home/milo/eternal_gallery/memory_b_cells.h5mu")

... storing 'feature_types' as categorical
... storing 'genome' as categorical
... storing 'subject_ref' as categorical
... storing 'self_race' as categorical